# Generated by Django 5.1.6 on 2025-04-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0012_chatuser_current_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatengine.chatbot')),
                ('chatuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatengine.chatuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
