# Generated by Django 5.1.6 on 2025-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0013_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
